// Generated by Haxe 3.4.7

#pragma warning disable 109, 114, 219, 429, 168, 162
namespace graph {
	public class EndPoint : global::haxe.lang.HxObject, global::serialization.ISerializable {
		
		public EndPoint(global::haxe.lang.EmptyObject empty) {
		}
		
		
		public EndPoint(global::haxe.lang.Null<int> nodeId, global::haxe.lang.Null<int> slotId) {
			global::graph.EndPoint.__hx_ctor_graph_EndPoint(this, nodeId, slotId);
		}
		
		
		public static void __hx_ctor_graph_EndPoint(global::graph.EndPoint __hx_this, global::haxe.lang.Null<int> nodeId, global::haxe.lang.Null<int> slotId) {
			unchecked {
				int __temp_slotId6 = ( ( ! (slotId.hasValue) ) ? (-1) : ((slotId).@value) );
				int __temp_nodeId5 = ( ( ! (nodeId.hasValue) ) ? (-1) : ((nodeId).@value) );
				__hx_this.nodeId = __temp_nodeId5;
				__hx_this.slotId = __temp_slotId6;
			}
		}
		
		
		public int nodeId;
		
		public int slotId;
		
		public virtual string SerializeToJson() {
			object endPoint = new global::haxe.lang.DynamicObject(new int[]{}, new object[]{}, new int[]{656559741, 1946687865}, new double[]{((double) (this.nodeId) ), ((double) (this.slotId) )});
			return global::haxe.format.JsonPrinter.print(endPoint, null, null);
		}
		
		
		public virtual void SeriralizeToBytes(global::haxe.io.Bytes bytes) {
		}
		
		
		public virtual void DeserializeFromJson(string json) {
			object endPoint = new global::haxe.format.JsonParser(((string) (json) )).parseRec();
			this.nodeId = ((int) (global::haxe.lang.Runtime.getField_f(endPoint, "nodeId", 656559741, true)) );
			this.slotId = ((int) (global::haxe.lang.Runtime.getField_f(endPoint, "slotId", 1946687865, true)) );
		}
		
		
		public virtual void DeserializeFromBytes(global::haxe.io.Bytes bytes) {
		}
		
		
		public override double __hx_setField_f(string field, int hash, double @value, bool handleProperties) {
			unchecked {
				switch (hash) {
					case 1946687865:
					{
						this.slotId = ((int) (@value) );
						return @value;
					}
					
					
					case 656559741:
					{
						this.nodeId = ((int) (@value) );
						return @value;
					}
					
					
					default:
					{
						return base.__hx_setField_f(field, hash, @value, handleProperties);
					}
					
				}
				
			}
		}
		
		
		public override object __hx_setField(string field, int hash, object @value, bool handleProperties) {
			unchecked {
				switch (hash) {
					case 1946687865:
					{
						this.slotId = ((int) (global::haxe.lang.Runtime.toInt(@value)) );
						return @value;
					}
					
					
					case 656559741:
					{
						this.nodeId = ((int) (global::haxe.lang.Runtime.toInt(@value)) );
						return @value;
					}
					
					
					default:
					{
						return base.__hx_setField(field, hash, @value, handleProperties);
					}
					
				}
				
			}
		}
		
		
		public override object __hx_getField(string field, int hash, bool throwErrors, bool isCheck, bool handleProperties) {
			unchecked {
				switch (hash) {
					case 1885040770:
					{
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "DeserializeFromBytes", 1885040770)) );
					}
					
					
					case 337619441:
					{
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "DeserializeFromJson", 337619441)) );
					}
					
					
					case 1630734736:
					{
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "SeriralizeToBytes", 1630734736)) );
					}
					
					
					case 1990209315:
					{
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "SerializeToJson", 1990209315)) );
					}
					
					
					case 1946687865:
					{
						return this.slotId;
					}
					
					
					case 656559741:
					{
						return this.nodeId;
					}
					
					
					default:
					{
						return base.__hx_getField(field, hash, throwErrors, isCheck, handleProperties);
					}
					
				}
				
			}
		}
		
		
		public override double __hx_getField_f(string field, int hash, bool throwErrors, bool handleProperties) {
			unchecked {
				switch (hash) {
					case 1946687865:
					{
						return ((double) (this.slotId) );
					}
					
					
					case 656559741:
					{
						return ((double) (this.nodeId) );
					}
					
					
					default:
					{
						return base.__hx_getField_f(field, hash, throwErrors, handleProperties);
					}
					
				}
				
			}
		}
		
		
		public override object __hx_invokeField(string field, int hash, global::Array dynargs) {
			unchecked {
				switch (hash) {
					case 1885040770:
					{
						this.DeserializeFromBytes(((global::haxe.io.Bytes) (dynargs[0]) ));
						break;
					}
					
					
					case 337619441:
					{
						this.DeserializeFromJson(global::haxe.lang.Runtime.toString(dynargs[0]));
						break;
					}
					
					
					case 1630734736:
					{
						this.SeriralizeToBytes(((global::haxe.io.Bytes) (dynargs[0]) ));
						break;
					}
					
					
					case 1990209315:
					{
						return this.SerializeToJson();
					}
					
					
					default:
					{
						return base.__hx_invokeField(field, hash, dynargs);
					}
					
				}
				
				return null;
			}
		}
		
		
		public override void __hx_getFields(global::Array<object> baseArr) {
			baseArr.push("slotId");
			baseArr.push("nodeId");
			base.__hx_getFields(baseArr);
		}
		
		
	}
}


