// Generated by Haxe 3.4.7

#pragma warning disable 109, 114, 219, 429, 168, 162
namespace core {
	public class Datum : global::haxe.lang.HxObject, global::serialization.ISerializable {
		
		public Datum(global::haxe.lang.EmptyObject empty) {
		}
		
		
		public Datum() {
			global::core.Datum.__hx_ctor_core_Datum(this);
		}
		
		
		public static void __hx_ctor_core_Datum(global::core.Datum __hx_this) {
		}
		
		
		public string name;
		
		public object @value;
		
		public virtual void Initialize(string name, object @value) {
			this.name = name;
			this.@value = @value;
		}
		
		
		public virtual bool As(global::core.Datum other) {
			if (string.Equals(this.name, other.name)) {
				return true;
			}
			
			return false;
		}
		
		
		public virtual string SerializeToJson() {
			object json = new global::haxe.lang.DynamicObject(new int[]{834174833, 1224700491}, new object[]{this.@value, this.name}, new int[]{}, new double[]{});
			return global::haxe.format.JsonPrinter.print(json, null, null);
		}
		
		
		public virtual void SeriralizeToBytes(global::haxe.io.Bytes bytes) {
		}
		
		
		public virtual void DeserializeFromJson(string json) {
			object obj = new global::haxe.format.JsonParser(((string) (json) )).parseRec();
			this.name = global::haxe.lang.Runtime.toString(global::haxe.lang.Runtime.getField(obj, "name", 1224700491, true));
			this.@value = global::haxe.lang.Runtime.getField(obj, "value", 834174833, true);
		}
		
		
		public virtual void DeserializeFromBytes(global::haxe.io.Bytes bytes) {
		}
		
		
		public override double __hx_setField_f(string field, int hash, double @value, bool handleProperties) {
			unchecked {
				switch (hash) {
					case 834174833:
					{
						this.@value = ((object) (@value) );
						return @value;
					}
					
					
					default:
					{
						return base.__hx_setField_f(field, hash, @value, handleProperties);
					}
					
				}
				
			}
		}
		
		
		public override object __hx_setField(string field, int hash, object @value, bool handleProperties) {
			unchecked {
				switch (hash) {
					case 834174833:
					{
						this.@value = ((object) (@value) );
						return @value;
					}
					
					
					case 1224700491:
					{
						this.name = global::haxe.lang.Runtime.toString(@value);
						return @value;
					}
					
					
					default:
					{
						return base.__hx_setField(field, hash, @value, handleProperties);
					}
					
				}
				
			}
		}
		
		
		public override object __hx_getField(string field, int hash, bool throwErrors, bool isCheck, bool handleProperties) {
			unchecked {
				switch (hash) {
					case 1885040770:
					{
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "DeserializeFromBytes", 1885040770)) );
					}
					
					
					case 337619441:
					{
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "DeserializeFromJson", 337619441)) );
					}
					
					
					case 1630734736:
					{
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "SeriralizeToBytes", 1630734736)) );
					}
					
					
					case 1990209315:
					{
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "SerializeToJson", 1990209315)) );
					}
					
					
					case 14610:
					{
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "As", 14610)) );
					}
					
					
					case 1668035952:
					{
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "Initialize", 1668035952)) );
					}
					
					
					case 834174833:
					{
						return this.@value;
					}
					
					
					case 1224700491:
					{
						return this.name;
					}
					
					
					default:
					{
						return base.__hx_getField(field, hash, throwErrors, isCheck, handleProperties);
					}
					
				}
				
			}
		}
		
		
		public override double __hx_getField_f(string field, int hash, bool throwErrors, bool handleProperties) {
			unchecked {
				switch (hash) {
					case 834174833:
					{
						return ((double) (global::haxe.lang.Runtime.toDouble(this.@value)) );
					}
					
					
					default:
					{
						return base.__hx_getField_f(field, hash, throwErrors, handleProperties);
					}
					
				}
				
			}
		}
		
		
		public override object __hx_invokeField(string field, int hash, global::Array dynargs) {
			unchecked {
				switch (hash) {
					case 1885040770:
					{
						this.DeserializeFromBytes(((global::haxe.io.Bytes) (dynargs[0]) ));
						break;
					}
					
					
					case 337619441:
					{
						this.DeserializeFromJson(global::haxe.lang.Runtime.toString(dynargs[0]));
						break;
					}
					
					
					case 1630734736:
					{
						this.SeriralizeToBytes(((global::haxe.io.Bytes) (dynargs[0]) ));
						break;
					}
					
					
					case 1990209315:
					{
						return this.SerializeToJson();
					}
					
					
					case 14610:
					{
						return this.As(((global::core.Datum) (dynargs[0]) ));
					}
					
					
					case 1668035952:
					{
						this.Initialize(global::haxe.lang.Runtime.toString(dynargs[0]), dynargs[1]);
						break;
					}
					
					
					default:
					{
						return base.__hx_invokeField(field, hash, dynargs);
					}
					
				}
				
				return null;
			}
		}
		
		
		public override void __hx_getFields(global::Array<object> baseArr) {
			baseArr.push("value");
			baseArr.push("name");
			base.__hx_getFields(baseArr);
		}
		
		
	}
}


